### ISSUE TITLE
Task in custom key hooks.php - Function name must be a string 

### ISSUE THREAD

**Issue by Soufraz** [rocketeers/rocketeer#618]
I am trying to create a task to run `composer install` on the remote server.
The task appears in rocketeer on terminal. But when I ran rocketeer composer:install, I get the error below:

```
rocketeer composer:install
| Closure
PHP Fatal error:  Function name must be a string in phar:///usr/local/bin/rocketeer/src/Rocketeer/Tasks/Closure.php on line 150
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/rocketeer:0
PHP   2. require() /usr/local/bin/rocketeer:16
PHP   3. Rocketeer\Facades\Console::run() phar:///usr/local/bin/rocketeer/bin/rocketeer:26
PHP   4. Illuminate\Support\Facades\Facade::__callStatic() phar:///usr/local/bin/rocketeer/bin/rocketeer:26
PHP   5. Symfony\Component\Console\Application->run() phar:///usr/local/bin/rocketeer/vendor/illuminate/support/Illuminate/Support/Facades/Facade.php:205
PHP   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/rocketeer/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/rocketeer/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   8. Illuminate\Console\Command->run() phar:///usr/local/bin/rocketeer/vendor/symfony/console/Symfony/Component/Console/Application.php:889
PHP   9. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/rocketeer/vendor/illuminate/console/Illuminate/Console/Command.php:100
PHP  10. Illuminate\Console\Command->execute() phar:///usr/local/bin/rocketeer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP  11. Rocketeer\Console\Commands\BaseTaskCommand->fire() phar:///usr/local/bin/rocketeer/vendor/illuminate/console/Illuminate/Console/Command.php:112
PHP  12. Rocketeer\Abstracts\AbstractCommand->fireTasksQueue() phar:///usr/local/bin/rocketeer/src/Rocketeer/Console/Commands/BaseTaskCommand.php:55
PHP  13. Rocketeer\Abstracts\AbstractCommand->time() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:176
PHP  14. Rocketeer\Abstracts\AbstractCommand->Rocketeer\Abstracts\{closure}() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:270
PHP  15. Rocketeer\Services\Tasks\TasksQueue->run() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:173
PHP  16. Rocketeer\Services\Tasks\TasksQueue->runSynchronously() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:130
PHP  17. Rocketeer\Services\Tasks\TasksQueue->Rocketeer\Services\Tasks\{closure}() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:222
PHP  18. Rocketeer\Services\Tasks\TasksQueue->executeJob() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:122
PHP  19. Rocketeer\Abstracts\AbstractTask->fire() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:190
PHP  20. Rocketeer\Services\Display\QueueTimer->time() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php:144
PHP  21. Rocketeer\Abstracts\AbstractTask->Rocketeer\Abstracts\{closure}() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Display/QueueTimer.php:39
PHP  22. Rocketeer\Tasks\Closure->execute() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php:143

Fatal error: Function name must be a string in phar:///usr/local/bin/rocketeer/src/Rocketeer/Tasks/Closure.php on line 150

Call Stack:
    0.0015     296384   1. {main}() /usr/local/bin/rocketeer:0
    0.0246     845576   2. require('phar:///usr/local/bin/rocketeer/bin/rocketeer') /usr/local/bin/rocketeer:16
    0.0325    1372656   3. Rocketeer\Facades\Console::run() phar:///usr/local/bin/rocketeer/bin/rocketeer:26
    0.0325    1372888   4. Illuminate\Support\Facades\Facade::__callStatic() phar:///usr/local/bin/rocketeer/bin/rocketeer:26
    0.1327    5176872   5. Symfony\Component\Console\Application->run() phar:///usr/local/bin/rocketeer/vendor/illuminate/support/Illuminate/Support/Facades/Facade.php:205
    0.1363    5490352   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/rocketeer/vendor/symfony/console/Symfony/Component/Console/Application.php:124
    0.1365    5491264   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/rocketeer/vendor/symfony/console/Symfony/Component/Console/Application.php:193
    0.1366    5491432   8. Illuminate\Console\Command->run() phar:///usr/local/bin/rocketeer/vendor/symfony/console/Symfony/Component/Console/Application.php:889
    0.1366    5491800   9. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/rocketeer/vendor/illuminate/console/Illuminate/Console/Command.php:100
    0.1372    5495656  10. Illuminate\Console\Command->execute() phar:///usr/local/bin/rocketeer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
    0.1372    5495720  11. Rocketeer\Console\Commands\BaseTaskCommand->fire() phar:///usr/local/bin/rocketeer/vendor/illuminate/console/Illuminate/Console/Command.php:112
    0.1373    5496088  12. Rocketeer\Abstracts\AbstractCommand->fireTasksQueue() phar:///usr/local/bin/rocketeer/src/Rocketeer/Console/Commands/BaseTaskCommand.php:55
    0.1434    5549536  13. Rocketeer\Abstracts\AbstractCommand->time() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:176
    0.1435    5549648  14. Rocketeer\Abstracts\AbstractCommand->Rocketeer\Abstracts\{closure}() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:270
    0.1440    5594880  15. Rocketeer\Services\Tasks\TasksQueue->run() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:173
    0.1492    5791504  16. Rocketeer\Services\Tasks\TasksQueue->runSynchronously() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:130
    0.1492    5792384  17. Rocketeer\Services\Tasks\TasksQueue->Rocketeer\Services\Tasks\{closure}() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:222
    0.1492    5792688  18. Rocketeer\Services\Tasks\TasksQueue->executeJob() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:122
    0.1501    5794112  19. Rocketeer\Abstracts\AbstractTask->fire() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:190
    0.1525    5847624  20. Rocketeer\Services\Display\QueueTimer->time() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php:144
    0.1525    5847704  21. Rocketeer\Abstracts\AbstractTask->Rocketeer\Abstracts\{closure}() phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Display/QueueTimer.php:39
    0.1525    5847736  22. Rocketeer\Tasks\Closure->execute() phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php:143

```

My custom key in hooks.php:

```
    // Custom Tasks to register with Rocketeer
    'custom' => [
        'composer:install' => 'composer install'
    ],
```

I am a tiny confused about tasks yet. Thank you advice..

**Comment by blade93ny** [comment]
take a look at strategies.php file...there should be a composer section

**Comment by Soufraz** [comment]
There is. But I wonder to know how can I create my own custom tasks. Composer was an example.

**Comment by Soufraz** [comment]
I found all that I need here: 
http://rocketeer.autopergamene.eu/api/namespaces/Rocketeer.Tasks.html
Thanks!

**Comment by publicarray** [comment]
Was this ever solved?  I have the same problem with the following custom tasks:

```php
// Custom Tasks to register with Rocketeer
    'custom' => [
        'down' => ['php artisan down'],
        'up' => ['php artisan up']
    ],
```

```
rocketeer down
| Closure
PHP Fatal error:  Uncaught Error: Function name must be a string in phar:///usr/local/bin/rocketeer/src/Rocketeer/Tasks/Closure.php:150
Stack trace:
#0 phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php(143): Rocketeer\Tasks\Closure->execute()
#1 phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Display/QueueTimer.php(39): Rocketeer\Abstracts\AbstractTask->Rocketeer\Abstracts\{closure}()
#2 phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php(144): Rocketeer\Services\Display\QueueTimer->time(Object(Rocketeer\Tasks\Closure), Object(Closure))
#3 phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php(190): Rocketeer\Abstracts\AbstractTask->fire()
#4 phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php(122): Rocketeer\Services\Tasks\TasksQueue->executeJob(Object(Rocketeer\Services\Tasks\Job))
#5 phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php(222): Rocketeer\Services\Tasks\TasksQueue->Rocketeer\Services\Tasks\{clo in phar:///usr/local/bin/rocketeer/src/Rocketeer/Tasks/Closure.php on line 150

Fatal error: Uncaught Error: Function name must be a string in phar:///usr/local/bin/rocketeer/src/Rocketeer/Tasks/Closure.php:150
Stack trace:
#0 phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php(143): Rocketeer\Tasks\Closure->execute()
#1 phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Display/QueueTimer.php(39): Rocketeer\Abstracts\AbstractTask->Rocketeer\Abstracts\{closure}()
#2 phar:///usr/local/bin/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php(144): Rocketeer\Services\Display\QueueTimer->time(Object(Rocketeer\Tasks\Closure), Object(Closure))
#3 phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php(190): Rocketeer\Abstracts\AbstractTask->fire()
#4 phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php(122): Rocketeer\Services\Tasks\TasksQueue->executeJob(Object(Rocketeer\Services\Tasks\Job))
#5 phar:///usr/local/bin/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php(222): Rocketeer\Services\Tasks\TasksQueue->Rocketeer\Services\Tasks\{clo in phar:///usr/local/bin/rocketeer/src/Rocketeer/Tasks/Closure.php on line 150
```

**Comment by publicarray** [comment]
Nevermind I just created 2 classes http://rocketeer.autopergamene.eu/#/docs/docs/II-Concepts/Tasks#via-classes

**Comment by lwrbakro** [comment]
How did you do it?
I created the .rocketeer/tasks/Migrate.php as this: http://rocketeer.autopergamene.eu/II-Concepts/Tasks.html#via-classes

After that I registered in the hooks.php as this:
```
'custom' => [
    'db:migrate' => 'MyTask\Migrate'
],
```

Still get the "Function name must be a string" error.

I am using rocketeer v2.0.7

**Comment by publicarray** [comment]
Hi @lwrbakro,
First of all I would update rocketeer. The reason it does not work for you is because your file path `.rocketeer/tasks/Migrate.php` does not match the class path `'MyTask\Migrate'` (in your hooks.php). 

To fix it you can change your folder name to `MyTask` so that the file path is `.rocketeer/MyTask/Migrate.php` or you can change the class path to `'task\Migrate'` and update your Migrate.php namespace from `MyTasks` to `Tasks`.
Hope this solves it.

**Comment by lwrbakro** [comment]
Thank you for your kind help.
It works now.

I think the "migrate" name confused the AI behind the argument perser of the console.

**Comment by Anahkiasen** [comment]
Yeah Rocketeer's file/class loading is kind of barbaric, my goal for R3 since it's going to be a bit more class-based is to hop onto Composer's autoloader and provide a PSR4 folder for users to put all their stuff in instead of this current mixed-bag system where some folders are loaded, some not, and you can't have subfolders, etc
